
public class TelaPrincipal extends javax.swing.JFrame {

    static int qtdFuncionarios = 0;
    static Funcionario vetor[] = new Funcionario[10];
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCadastrosFuncionarios = new javax.swing.JMenuItem();
        jMenuListagens = new javax.swing.JMenu();
        jMenuItemListagensFuncionarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas de Carros");

        jMenuCadastros.setText("Cadastros");
        jMenuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrosActionPerformed(evt);
            }
        });

        jMenuItemCadastrosFuncionarios.setText("Funcionario");
        jMenuItemCadastrosFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrosFuncionariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastrosFuncionarios);

        jMenuBar1.add(jMenuCadastros);

        jMenuListagens.setText("Listagens");
        jMenuListagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListagensActionPerformed(evt);
            }
        });

        jMenuItemListagensFuncionarios.setText("Funcionarios");
        jMenuItemListagensFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListagensFuncionariosActionPerformed(evt);
            }
        });
        jMenuListagens.add(jMenuItemListagensFuncionarios);

        jMenuBar1.add(jMenuListagens);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrosFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrosFuncionariosActionPerformed
        TelaCadastroFuncionarios objTelaCadastroFuncionarios = new TelaCadastroFuncionarios();
        this.jDesktopPane1.add(objTelaCadastroFuncionarios);
        objTelaCadastroFuncionarios.show();
    }//GEN-LAST:event_jMenuItemCadastrosFuncionariosActionPerformed

    private void jMenuItemListagensFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListagensFuncionariosActionPerformed
        TelaListagemFuncionarios objTelaListagemFuncionarios = new TelaListagemFuncionarios();
        this.jDesktopPane1.add(objTelaListagemFuncionarios);
        objTelaListagemFuncionarios.show();
    }//GEN-LAST:event_jMenuItemListagensFuncionariosActionPerformed

    private void jMenuListagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListagensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuListagensActionPerformed

    private void jMenuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCadastrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItemCadastrosFuncionarios;
    private javax.swing.JMenuItem jMenuItemListagensFuncionarios;
    private javax.swing.JMenu jMenuListagens;
    // End of variables declaration//GEN-END:variables
}
